# Generated by Django 5.0.6 on 2024-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(blank=True, max_length=50, null=True)),
                ('Emailid', models.CharField(blank=True, max_length=50, null=True)),
                ('Passw', models.IntegerField(blank=True, null=True)),
                ('Poimage', models.ImageField(blank=True, null=True, upload_to='Prof_Images')),
            ],
        ),
    ]
