# Generated by Django 5.0.6 on 2024-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_shipingdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
