# Generated by Django 5.0.6 on 2024-06-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_shipingdb_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
